### ISSUE TITLE
Push the last version into npm

### ISSUE THREAD

**Issue by kolegm** [kolegm/racer-rpc#3]
As I see on [npm/racer-rpc](https://www.npmjs.com/package/racer-rpc) last changes were pushed 3 years ago.
Please, push the last version to npm storage

**Comment by cjblomqvist** [comment]
@kolegm - would you like to become the owner of the package?

**Comment by kolegm** [comment]
Ok, if you are ready so easy to give me the package mantaining.
Do you use it on your side?

And another question is, do you use Derbyjs today, if not then why?

**Comment by cjblomqvist** [comment]
@kolegm - kolegm/racer-rpc already exists, so can't make the transfer.

Not using Derby today. Due to lack of velocity, maintenance, willingness to get help from the community, etc. so I decided to not use it for new projects. The projects I/we used Derby for has been sold or shut down.

**Comment by kolegm** [comment]
ok, I have removed forked repo `kolegm/racer-rpc`. Could you make a transfer now?
And I'm interested in access to npm racer-rpc too.

**Comment by cjblomqvist** [comment]
Done! Probably awaiting your approval!

I've added you as an owner to npm racer-rpc as well.
